In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,
                 2,
                 3])
print(arr1)
print(arr1.shape)

[1 2 3]
(3,)


In [26]:
np.convolve(np.array([1,2,3]), np.array([4,5]))

array([ 4, 13, 22, 15])

In [4]:
average_mask = 1/9*np.array([[1,1,1],
                         [1,1,1],
                         [1,1,1]])
print(average_mask)
print(average_mask.shape)

[[0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]]
(3, 3)


In [13]:
vertical_edge_mask = np.array([[1,0,-1],
                               [1,0,-1],
                               [1,0,-1]])
print(type(vertical_edge_mask[0][0]))
image = np.array([[10, 10, 10, 0, 0, 0], 
                  [10, 10, 10, 0, 0, 0], 
                  [10, 10, 10, 0, 0, 0], 
                  [10, 10, 10, 0, 0, 0], 
                  [10, 10, 10, 0, 0, 0], 
                  [10, 10, 10, 0, 0, 0]])


<class 'numpy.int64'>


In [6]:
from scipy import signal

In [14]:
image2 = signal.convolve2d(image, vertical_edge_mask, mode = "valid", boundary = "fill", fillvalue=0)
print(image2)


[[  0 -30 -30   0]
 [  0 -30 -30   0]
 [  0 -30 -30   0]
 [  0 -30 -30   0]]
[[ 1  0 -1]
 [ 1  0 -1]
 [ 1  0 -1]]


In [15]:
from scipy import ndimage

In [17]:
image3 = ndimage.convolve(image, vertical_edge_mask[::-1,::-1])
print(image3)

[[ 0  0 30 30  0  0]
 [ 0  0 30 30  0  0]
 [ 0  0 30 30  0  0]
 [ 0  0 30 30  0  0]
 [ 0  0 30 30  0  0]
 [ 0  0 30 30  0  0]]
